#!/bin/sh
cat <<'EMBED' >/tmp/documents/help.md
###########################
help: single-contained shellscripts
Unlicensed
###########################
EMBED
cat <<'EMBED' >/tmp/scripts/compile.sh
#!/bin/sh

embed_document() {
  while read -r line; do
    echo 'cat <<'\'EMBED\'' >/tmp/'"$line" >/tmp/tmp_header
    echo "EMBED" >/tmp/tmp_footer
    grep ^ "$line" |
      cat /tmp/tmp_header - /tmp/tmp_footer
  done
}

find ./ -type d |
  grep -e "documents" -e "scripts" |
  sed "s|./|/tmp/|" |
  xargs mkdir

echo '#!/bin/sh' >test_script

: 'Export documents' && {
  find documents/*.md |
    embed_document |
    grep -v '```'
} >>test_script

: 'Export scripts' && {
  find scripts/* |
    embed_document
} >>test_script

: 'main' && {
  echo 'ARGS="$*" && export ARGS' >>test_script
  find scripts/ -type f |
    grep -v "compile" |
    sed "s|^|. /tmp/|" >>test_script
}

chmod +x test_script

./test_script -h

rm /tmp/tmp_*
EMBED
cat <<'EMBED' >/tmp/scripts/help.sh
#!/bin/sh

set -ue
umask 0022
export LC_ALL=C

set -- $ARGS

[ "$#" -eq 0 ] && grep -v '```' /tmp/documents/help.md && exit 0

[ "_$1" = "_-h" ] && grep -v '```' /tmp/documents/help.md && exit 0

echo "Unrecognized option: $1" && exit 1
EMBED
ARGS="$*" && export ARGS
. /tmp/scripts/help.sh
