#!/bin/sh
set -ue
mkdir -p /tmp/documents
mkdir -p /tmp/scripts
cat <<'EMBED' >/tmp/documents/help.md
###########################
help: self-contained shellscripts
Unlicensed
https://github.com/akikuno/self-contained-shellscript
###########################
EMBED
cat <<'EMBED' >/tmp/scripts/help.sh
#!/bin/sh

set -ue
umask 0022
export LC_ALL=C

set -- $ARGS

if [ "$#" -eq 0 ]; then
  grep -v '```' /tmp/documents/help.md
elif [ "_$1" = "_-h" ]; then
  grep -v '```' /tmp/documents/help.md
else
  echo "Unrecognized option: $1" && exit 1
fi
EMBED
ARGS="$*" && export ARGS
. /tmp/scripts/help.sh
rm -rf /tmp/documents /tmp/scripts/
