#!/bin/sh
set -ue
mkdir -p /tmp/documents
mkdir -p /tmp/scripts
cat <<'EMBED' >/tmp/documents/help.md
###########################
help: self-contained shellscripts
Unlicensed
https://github.com/akikuno/self-contained-shellscript
###########################
EMBED
cat <<'EMBED' >/tmp/scripts/compile.sh
#!/bin/sh

embed_document() {
  while read -r line; do
    echo 'cat <<'\'EMBED\'' >/tmp/'"$line" >/tmp/tmp_header
    echo "EMBED" >/tmp/tmp_footer
    grep ^ "$line" |
      cat /tmp/tmp_header - /tmp/tmp_footer
  done
}

echo '#!/bin/sh' >selfcontained
echo 'set -ue' >>selfcontained

: 'Create directories' && {
  find ./ -type d |
    grep -e "documents" -e "scripts" |
    sed "s|./|mkdir -p /tmp/|"
} >>selfcontained

: 'Export documents' && {
  find documents/*.md |
    embed_document |
    grep -v '```'
} >>selfcontained

: 'Export scripts' && {
  find scripts/* |
    embed_document
} >>selfcontained

: 'main' && {
  echo 'ARGS="$*" && export ARGS' >>selfcontained
  find scripts/ -type f |
    grep -v "compile" |
    sed "s|^|. /tmp/|" >>selfcontained
}

: 'cleanup' && {
  echo 'rm -rf /tmp/documents /tmp/scripts/' >>selfcontained
}
chmod +x selfcontained

./selfcontained -h

rm /tmp/tmp_*
EMBED
cat <<'EMBED' >/tmp/scripts/help.sh
#!/bin/sh

set -ue
umask 0022
export LC_ALL=C

set -- $ARGS

if [ "$#" -eq 0 ]; then
  grep -v '```' /tmp/documents/help.md
elif [ "_$1" = "_-h" ]; then
  grep -v '```' /tmp/documents/help.md
else
  echo "Unrecognized option: $1" && exit 1
fi
EMBED
ARGS="$*" && export ARGS
. /tmp/scripts/help.sh
rm -rf /tmp/documents /tmp/scripts/
